FROM node:14
# NODE NA VERSÃO 14 COMO BASE PARA A APLICAÇÃO
WORKDIR /app-node
# DEFINIR O DIRETÓRIO PADRÃO COMO SENDO /APP-NODE
ARG PORT_BUILD=5000
# DEFININDO A PORTA 6000 POR UMA VÁRIÁVEL (EM TEMPO DE BUILD DA IMAGEM)
ENV PORT=$PORT_BUILD
# AGORA EU PEGO A MINHA PORTA QUE SERÁ USADA EM TEMPO DE BUILD E JOGO PARA DENTRO DA ENV DA APLICAÇÃO
EXPOSE $PORT_BUILD
# EXPONDO A PORTA 3000
COPY . .
# VAMOS COPIAR ESSA PARTA APP-EXEMPLO PARA O DIRETÓRIO DEFINIDO ANTERIORMENTE
# O PRIMEIRO PONTINHO É A PASTA APP-EXEMPLO E O SEGUNDO É O DIRETÓRIO NOVO
RUN npm install
# EXECUTAR ESSE COMANDO ENQUANTO A IMAGEM ESTIVER ->>> SENDO CRIADA
ENTRYPOINT npm run serve
# QUANDO CRIADA, ESSE COMANDO SERÁ EXECUTADO
# docker build -t jao/app-node:1 .
# esse ponto no final é no contexto do diretório final